# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    docker:
      - image: cimg/openjdk:8.0
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: Test
          command: mvn clean verify
      - store_artifacts:
                path: ~/project/target/site/serenity

workflows:
  run-api-tests:
    jobs:
      - test
